baseurl = "http://juliocesarbatista.com/"
title = "Júlio César Batista"
author = "Júlio César Batista"
copyright = "Copyright (c) 2016 Júlio César Batista"
canonifyurls = true
paginate = 3
theme="finite"

[params]

# Date format (refer to Go's date format: http://flippinggodateformat.com)
# Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "2006/01/02"

# Publications can have a Params.publication for citation references.
# Publications can have a Params.kind, such as "book".
# Both parameters are mapped to an icon in partials/pub-icon.html.

about = "Olá, meu nome é Júlio César Batista. Eu desenvolvo softwares. Atualmente sou pesquisador no [IMAGO Research Group - UFPR](http://www.imago.ufpr.br); ~~desenvolvedor na [Inventti](http://www.inventti.com.br)~~; ~~desenvolvedor na [Ellevo](http://www.ellevo.com)~~. Também sou mestrando em informática pela [UFPR](http://ufpr.br) e bacharel em ciência da computação pela [FURB](http://www.furb.br). É um prazer conhecê-lo, seja bem-vindo."
bio_twitter = "ejuliobatista"

# Title of posts section on main page.
#posts_title = "Posts"

# Number of posts to show on main page.
#posts_count = 2

# Title of publications section on main page.
pubs_title = "Publicações"

# Number of publications to show on main page.
#pubs_count = 5

[[params.education]]
  course = "M. Sc. em Informática"
  institution = "Universidade Federal do Paraná - UFPR"
  year = 2018

[[params.education]]
  course = "B. Sc. em Ciência da Computação"
  institution = "Universidade Regional de Blumenau - FURB"
  year = 2015

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:julio.batista@outlook.com"
  text = "julio.batista@outlook.com "
    
[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/ejuliobatista"
  text = "@ejuliobatista"
  site = "Twitter"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "https://github.com/ejulio"
  text = "ejulio"
  site = "GitHub"

# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Publicações"
  url = "/publication/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 3

[[menu.main]]
  name = "Recursos"
  url = "/logbook/"
  weight = 4