baseURL = "https://juliocesarbatista.com"
title = "Júlio César Batista"
theme = "hugo-coder"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Júlio César Batista"
description = "Some description"
keywords = "blog,software,developer"
info = ["Software Developer"]
avatarURL = "img/portrait.jpg"
dateFormat = "2006-01-02"
since = 2016
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/ejulio/"
target = "_blank"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/juliobatista/"
target = "_blank"

[[params.social]]
name = "CV"
icon = "fa fa-2x fa-file"
weight = 4
url = "docs/cv.pdf"
target = "_blank"

[languages.pt-br]
languageName = ":brazil:"

[[menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[menu.main]]
name = "Publicações"
weight = 2
url = "categories/publicação/"

[[menu.main]]
name = "Blog"
weight = 3
url = "posts/"

[[menu.main]]
name = "Categorias"
weight = 4
url = "categories/"

# [[languages.pt-br.menu.main]]
# name = "Projetos"
# weight = 3
# url = "projects/"

# [[languages.pt-br.menu.main]]
# name = "Contato"
# weight = 5
# url = "contact/"